# Generated by Django 2.2.8 on 2020-12-30 16:43

from django.db import migrations
from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):
    User.objects.create_superuser('admin', password='@dm1n', email='')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191015_0853'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
